export type SongRecommendation = {
  title: string;
  artist: string;
  tag: string;
  coverTone: string;
};

export const SONGS: SongRecommendation[] = [
  { title: "Bling-Bang-Bang-Born", artist: "Creepy Nuts", tag: "Hot", coverTone: "pink" },
  { title: "Otonoke", artist: "Creepy Nuts", tag: "Anime", coverTone: "orange" },
  { title: "Nobishiro", artist: "Creepy Nuts", tag: "Groove", coverTone: "green" },
  { title: "Idol", artist: "YOASOBI", tag: "Hit", coverTone: "blue" },
  { title: "Yoru ni Kakeru", artist: "YOASOBI", tag: "Hit", coverTone: "sky" },
  { title: "Gunjo", artist: "YOASOBI", tag: "Pop", coverTone: "blue" },
  { title: "Adventure", artist: "YOASOBI", tag: "Pop", coverTone: "green" },
  { title: "The Blessing", artist: "YOASOBI", tag: "Anime", coverTone: "purple" },
  { title: "Monster", artist: "YOASOBI", tag: "Anime", coverTone: "black" },
  { title: "Heart Beat", artist: "YOASOBI", tag: "Pop", coverTone: "pink" },
  { title: "SPECIALZ", artist: "King Gnu", tag: "Popular", coverTone: "black" },
  { title: "Hakujitsu", artist: "King Gnu", tag: "Classic", coverTone: "mint" },
  { title: "Ichizu", artist: "King Gnu", tag: "Anime", coverTone: "purple" },
  { title: "Sakayume", artist: "King Gnu", tag: "Anime", coverTone: "sky" },
  { title: "Teenager Forever", artist: "King Gnu", tag: "Rock", coverTone: "red" },
  { title: "Show", artist: "Ado", tag: "Energy", coverTone: "red" },
  { title: "Usseewa", artist: "Ado", tag: "Energy", coverTone: "black" },
  { title: "New Genesis", artist: "Ado", tag: "Anime", coverTone: "red" },
  { title: "Odo", artist: "Ado", tag: "Dance", coverTone: "orange" },
  { title: "Gira Gira", artist: "Ado", tag: "Pop", coverTone: "purple" },
  { title: "Lemon", artist: "Kenshi Yonezu", tag: "Classic", coverTone: "yellow" },
  { title: "KICK BACK", artist: "Kenshi Yonezu", tag: "Anime", coverTone: "orange" },
  { title: "Peace Sign", artist: "Kenshi Yonezu", tag: "Anime", coverTone: "blue" },
  { title: "Eine Kleine", artist: "Kenshi Yonezu", tag: "Classic", coverTone: "mint" },
  { title: "M87", artist: "Kenshi Yonezu", tag: "Movie", coverTone: "sky" },
  { title: "Pretender", artist: "Official HIGE DANDism", tag: "Classic", coverTone: "mint" },
  { title: "Subtitle", artist: "Official HIGE DANDism", tag: "Ballad", coverTone: "mint" },
  { title: "Mixed Nuts", artist: "Official HIGE DANDism", tag: "Anime", coverTone: "orange" },
  { title: "I Love...", artist: "Official HIGE DANDism", tag: "Pop", coverTone: "pink" },
  { title: "Cry Baby", artist: "Official HIGE DANDism", tag: "Anime", coverTone: "red" },
  { title: "Shinunoga E-Wa", artist: "Fujii Kaze", tag: "Viral", coverTone: "black" },
  { title: "Matsuri", artist: "Fujii Kaze", tag: "Groove", coverTone: "green" },
  { title: "Kirari", artist: "Fujii Kaze", tag: "Pop", coverTone: "sky" },
  { title: "Kaikai Kitan", artist: "Eve", tag: "Anime", coverTone: "blue" },
  { title: "Ao no Waltz", artist: "Eve", tag: "Mood", coverTone: "sky" },
  { title: "Dramaturgy", artist: "Eve", tag: "Vocaloid", coverTone: "purple" },
  { title: "Gurenge", artist: "LiSA", tag: "Anime", coverTone: "red" },
  { title: "Homura", artist: "LiSA", tag: "Ballad", coverTone: "orange" },
  { title: "Crossing Field", artist: "LiSA", tag: "Anime", coverTone: "blue" },
  { title: "Zankyosanka", artist: "Aimer", tag: "Anime", coverTone: "purple" },
  { title: "Kataomoi", artist: "Aimer", tag: "Ballad", coverTone: "pink" },
  { title: "Brave Shine", artist: "Aimer", tag: "Anime", coverTone: "black" },
  { title: "Marigold", artist: "Aimyon", tag: "Classic", coverTone: "yellow" },
  { title: "Ai wo Tsutaetaidatoka", artist: "Aimyon", tag: "Pop", coverTone: "green" },
  { title: "Hadaka no Kokoro", artist: "Aimyon", tag: "Ballad", coverTone: "mint" },
  { title: "Betelgeuse", artist: "Yuuri", tag: "Ballad", coverTone: "sky" },
  { title: "Dry Flower", artist: "Yuuri", tag: "Ballad", coverTone: "mint" },
  { title: "Leo", artist: "Yuuri", tag: "Ballad", coverTone: "yellow" },
  { title: "W/X/Y", artist: "Tani Yuuki", tag: "Viral", coverTone: "blue" },
  { title: "Habit", artist: "SEKAI NO OWARI", tag: "Dance", coverTone: "red" },
  { title: "RPG", artist: "SEKAI NO OWARI", tag: "Classic", coverTone: "green" },
  { title: "Silent", artist: "SEKAI NO OWARI", tag: "Pop", coverTone: "sky" },
  { title: "Unravel", artist: "TK from Ling tosite sigure", tag: "Anime", coverTone: "black" },
  { title: "Inferno", artist: "Mrs. GREEN APPLE", tag: "Anime", coverTone: "orange" },
  { title: "Dance Hall", artist: "Mrs. GREEN APPLE", tag: "Pop", coverTone: "green" },
  { title: "Lilac", artist: "Mrs. GREEN APPLE", tag: "Hit", coverTone: "purple" },
  { title: "Que Sera Sera", artist: "Mrs. GREEN APPLE", tag: "Hit", coverTone: "mint" },
  { title: "Ao to Natsu", artist: "Mrs. GREEN APPLE", tag: "Summer", coverTone: "sky" },
  { title: "Hana ni Natte", artist: "Ryokuoushoku Shakai", tag: "Anime", coverTone: "pink" },
  { title: "Mela!", artist: "Ryokuoushoku Shakai", tag: "Energy", coverTone: "yellow" },
  { title: "Shout Baby", artist: "Ryokuoushoku Shakai", tag: "Anime", coverTone: "green" },
  { title: "Beautiful Fin", artist: "Spitz", tag: "Pop", coverTone: "sky" },
  { title: "Cherry", artist: "Spitz", tag: "Classic", coverTone: "pink" },
  { title: "Robinson", artist: "Spitz", tag: "Classic", coverTone: "mint" },
  { title: "Suiheisen", artist: "back number", tag: "Ballad", coverTone: "blue" },
  { title: "Christmas Song", artist: "back number", tag: "Classic", coverTone: "mint" },
  { title: "Happy End", artist: "back number", tag: "Ballad", coverTone: "pink" },
  { title: "Kaiju no Hanauta", artist: "Vaundy", tag: "Popular", coverTone: "green" },
  { title: "Odoriko", artist: "Vaundy", tag: "Groove", coverTone: "purple" },
  { title: "Tokyo Flash", artist: "Vaundy", tag: "Mood", coverTone: "black" },
  { title: "Chainsaw Blood", artist: "Vaundy", tag: "Anime", coverTone: "red" },
  { title: "Where Our Blue Is", artist: "Tatsuya Kitani", tag: "Anime", coverTone: "sky" },
  { title: "When The Weak Go Marching In", artist: "Tatsuya Kitani", tag: "Rock", coverTone: "black" },
  { title: "Phony", artist: "Tsumiki", tag: "Vocaloid", coverTone: "pink" },
  { title: "Goodbye Sengen", artist: "Chinozo", tag: "Vocaloid", coverTone: "yellow" },
  { title: "Vampire", artist: "DECO*27", tag: "Vocaloid", coverTone: "red" },
  { title: "Animal", artist: "DECO*27", tag: "Vocaloid", coverTone: "orange" },
  { title: "Lost One's Weeping", artist: "Neru", tag: "Vocaloid", coverTone: "black" },
  { title: "King", artist: "Kanaria", tag: "Vocaloid", coverTone: "purple" },
  { title: "Identity", artist: "Kanaria", tag: "Vocaloid", coverTone: "green" },
  { title: "Telecaster B-Boy", artist: "Surii", tag: "Vocaloid", coverTone: "blue" },
  { title: "Venom", artist: "Kairiki Bear", tag: "Vocaloid", coverTone: "red" },
  { title: "Darling Dance", artist: "Kairiki Bear", tag: "Vocaloid", coverTone: "pink" },
  { title: "Roki", artist: "MikitoP", tag: "Vocaloid", coverTone: "orange" },
  { title: "Charles", artist: "Balloon", tag: "Vocaloid", coverTone: "sky" },
  { title: "Rain and Petra", artist: "Balloon", tag: "Vocaloid", coverTone: "blue" },
  { title: "Ghost Rule", artist: "DECO*27", tag: "Vocaloid", coverTone: "black" },
  { title: "Hibana", artist: "DECO*27", tag: "Vocaloid", coverTone: "red" },
  { title: "Senbonzakura", artist: "Kurousa-P", tag: "Vocaloid", coverTone: "pink" },
  { title: "Tell Your World", artist: "livetune", tag: "Vocaloid", coverTone: "sky" },
  { title: "Melt", artist: "ryo", tag: "Vocaloid", coverTone: "mint" },
  { title: "World is Mine", artist: "ryo", tag: "Vocaloid", coverTone: "blue" },
  { title: "Rolling Girl", artist: "wowaka", tag: "Vocaloid", coverTone: "black" },
  { title: "Unknown Mother Goose", artist: "wowaka", tag: "Vocaloid", coverTone: "purple" },
  { title: "Dune", artist: "Hachi", tag: "Vocaloid", coverTone: "yellow" },
  { title: "Matryoshka", artist: "Hachi", tag: "Vocaloid", coverTone: "green" },
  { title: "Aishite Aishite Aishite", artist: "Kikuo", tag: "Vocaloid", coverTone: "purple" },
  { title: "Lagtrain", artist: "inabakumori", tag: "Vocaloid", coverTone: "sky" },
  { title: "Marshall Maximizer", artist: "Hiiragi Magnetite", tag: "Vocaloid", coverTone: "orange" },
  { title: "God-ish", artist: "PinocchioP", tag: "Vocaloid", coverTone: "red" },
  { title: "Non-breath Oblige", artist: "PinocchioP", tag: "Vocaloid", coverTone: "black" },
  { title: "Love Trial", artist: "40mP", tag: "Vocaloid", coverTone: "pink" },
  { title: "Karakuri Pierrot", artist: "40mP", tag: "Vocaloid", coverTone: "mint" },
  { title: "NIGHT DANCER", artist: "imase", tag: "Viral", coverTone: "purple" },
  { title: "Nagisa", artist: "imase", tag: "Pop", coverTone: "sky" },
  { title: "Overdose", artist: "natori", tag: "Viral", coverTone: "green" },
  { title: "Friday Night", artist: "natori", tag: "Groove", coverTone: "black" },
  { title: "Dried Flower", artist: "Yuuri", tag: "Ballad", coverTone: "mint" },
  { title: "Haru wo Tsugeru", artist: "yama", tag: "Viral", coverTone: "blue" },
  { title: "Oz.", artist: "yama", tag: "Anime", coverTone: "sky" },
  { title: "Neko", artist: "DISH//", tag: "Ballad", coverTone: "yellow" },
  { title: "No.1", artist: "DISH//", tag: "Anime", coverTone: "red" },
  { title: "Stand By Me Stand By You", artist: "HIRAIDAI", tag: "Chill", coverTone: "mint" },
  { title: "MIRROR MIRROR", artist: "HIRAIDAI", tag: "Chill", coverTone: "sky" },
  { title: "Cinderella Boy", artist: "Saucy Dog", tag: "Band", coverTone: "pink" },
  { title: "Itsuka", artist: "Saucy Dog", tag: "Band", coverTone: "green" },
  { title: "Dai Zero Kan", artist: "10-FEET", tag: "Movie", coverTone: "red" },
  { title: "Fin", artist: "10-FEET", tag: "Rock", coverTone: "black" },
  { title: "Sparkle", artist: "RADWIMPS", tag: "Movie", coverTone: "sky" },
  { title: "Zenzenzense", artist: "RADWIMPS", tag: "Movie", coverTone: "blue" },
  { title: "Nandemonaiya", artist: "RADWIMPS", tag: "Movie", coverTone: "mint" },
  { title: "Suzume", artist: "RADWIMPS feat. Toaka", tag: "Movie", coverTone: "orange" },
  { title: "Grand Escape", artist: "RADWIMPS feat. Toko Miura", tag: "Movie", coverTone: "sky" },
  { title: "Himawari no Yakusoku", artist: "Motohiro Hata", tag: "Classic", coverTone: "yellow" },
  { title: "Uroko", artist: "Motohiro Hata", tag: "Ballad", coverTone: "blue" },
  { title: "One More Time, One More Chance", artist: "Masayoshi Yamazaki", tag: "Classic", coverTone: "mint" },
  { title: "Plastic Love", artist: "Mariya Takeuchi", tag: "City Pop", coverTone: "pink" },
  { title: "Mayonaka no Door", artist: "Miki Matsubara", tag: "City Pop", coverTone: "purple" },
  { title: "Ride on Time", artist: "Tatsuro Yamashita", tag: "City Pop", coverTone: "sky" },
  { title: "Sparkle", artist: "Tatsuro Yamashita", tag: "City Pop", coverTone: "green" },
  { title: "Stay With Me", artist: "Miki Matsubara", tag: "City Pop", coverTone: "orange" },
  { title: "Sweet Soul Revue", artist: "Pizzicato Five", tag: "City Pop", coverTone: "pink" },
  { title: "Tokyo wa Yoru no Shichiji", artist: "Pizzicato Five", tag: "City Pop", coverTone: "black" },
  { title: "Automatic", artist: "Hikaru Utada", tag: "Classic", coverTone: "blue" },
  { title: "First Love", artist: "Hikaru Utada", tag: "Classic", coverTone: "mint" },
  { title: "One Last Kiss", artist: "Hikaru Utada", tag: "Anime", coverTone: "pink" },
  { title: "Flavor Of Life", artist: "Hikaru Utada", tag: "Ballad", coverTone: "purple" },
  { title: "Blue Bird", artist: "Ikimonogakari", tag: "Anime", coverTone: "blue" },
  { title: "Arigatou", artist: "Ikimonogakari", tag: "Classic", coverTone: "green" },
  { title: "Sakura", artist: "Ikimonogakari", tag: "Classic", coverTone: "pink" },
  { title: "Silhouette", artist: "KANA-BOON", tag: "Anime", coverTone: "orange" },
  { title: "Baton Road", artist: "KANA-BOON", tag: "Anime", coverTone: "red" },
  { title: "Haruka Kanata", artist: "ASIAN KUNG-FU GENERATION", tag: "Anime", coverTone: "black" },
  { title: "Rewrite", artist: "ASIAN KUNG-FU GENERATION", tag: "Anime", coverTone: "green" },
  { title: "Re:Re:", artist: "ASIAN KUNG-FU GENERATION", tag: "Rock", coverTone: "sky" },
  { title: "Sugar Song and Bitter Step", artist: "UNISON SQUARE GARDEN", tag: "Anime", coverTone: "yellow" },
  { title: "Orion wo Nazoru", artist: "UNISON SQUARE GARDEN", tag: "Anime", coverTone: "blue" },
  { title: "Kyouran Hey Kids!!", artist: "THE ORAL CIGARETTES", tag: "Anime", coverTone: "red" },
  { title: "BLACK MEMORY", artist: "THE ORAL CIGARETTES", tag: "Rock", coverTone: "black" },
  { title: "Fiction", artist: "sumika", tag: "Anime", coverTone: "green" },
  { title: "Lovers", artist: "sumika", tag: "Pop", coverTone: "pink" },
  { title: "Shake & Shake", artist: "sumika", tag: "Pop", coverTone: "orange" },
  { title: "Koi", artist: "Gen Hoshino", tag: "Classic", coverTone: "yellow" },
  { title: "Comedy", artist: "Gen Hoshino", tag: "Anime", coverTone: "mint" },
  { title: "SUN", artist: "Gen Hoshino", tag: "Pop", coverTone: "sky" },
  { title: "Soranji", artist: "Mrs. GREEN APPLE", tag: "Ballad", coverTone: "purple" },
  { title: "In the Morning", artist: "Mrs. GREEN APPLE", tag: "Band", coverTone: "green" },
  { title: "StaRt", artist: "Mrs. GREEN APPLE", tag: "Band", coverTone: "orange" },
  { title: "I Love You", artist: "Yutaka Ozaki", tag: "Classic", coverTone: "black" },
  { title: "Oh My Little Girl", artist: "Yutaka Ozaki", tag: "Classic", coverTone: "mint" },
  { title: "Sotsugyou", artist: "Yutaka Ozaki", tag: "Classic", coverTone: "blue" },
  { title: "Kawaranai Mono", artist: "Hanako Oku", tag: "Movie", coverTone: "pink" },
  { title: "Garnet", artist: "Hanako Oku", tag: "Movie", coverTone: "red" },
  { title: "Secret Base", artist: "ZONE", tag: "Classic", coverTone: "sky" },
  { title: "Hanabi", artist: "Mr.Children", tag: "Classic", coverTone: "orange" },
  { title: "Sign", artist: "Mr.Children", tag: "Classic", coverTone: "mint" },
  { title: "Tomorrow Never Knows", artist: "Mr.Children", tag: "Classic", coverTone: "blue" },
  { title: "Dry Flower", artist: "Yorushika", tag: "Mood", coverTone: "green" },
  { title: "That's Why I Gave Up on Music", artist: "Yorushika", tag: "Band", coverTone: "sky" },
  { title: "Just a Sunny Day for You", artist: "Yorushika", tag: "Band", coverTone: "yellow" },
  { title: "Hitchcock", artist: "Yorushika", tag: "Band", coverTone: "purple" },
  { title: "Cinema", artist: "Ayase", tag: "Vocaloid", coverTone: "blue" },
  { title: "Yuurei Tokyo", artist: "Ayase", tag: "Vocaloid", coverTone: "black" },
  { title: "HEART BEAT", artist: "YOASOBI", tag: "Pop", coverTone: "red" },
  { title: "Hare Hare", artist: "TWICE", tag: "Pop", coverTone: "sky" },
  { title: "Celebrate", artist: "TWICE", tag: "Pop", coverTone: "pink" },
  { title: "Doughnut", artist: "TWICE", tag: "Ballad", coverTone: "mint" },
  { title: "Perfect World", artist: "TWICE", tag: "Dance", coverTone: "purple" },
  { title: "Candy Pop", artist: "TWICE", tag: "Pop", coverTone: "yellow" },
  { title: "Voltage", artist: "ITZY", tag: "Dance", coverTone: "red" },
  { title: "Blah Blah Blah", artist: "ITZY", tag: "Dance", coverTone: "black" },
  { title: "Suki Lie", artist: "ATARASHII GAKKO!", tag: "Dance", coverTone: "orange" },
  { title: "Otonablue", artist: "ATARASHII GAKKO!", tag: "Viral", coverTone: "blue" },
  { title: "Tokyo Calling", artist: "ATARASHII GAKKO!", tag: "Dance", coverTone: "red" },
  { title: "Hai Yorokonde", artist: "Kocchi no Kento", tag: "Viral", coverTone: "yellow" },
  { title: "Mo-Eh-Wa", artist: "Kocchi no Kento", tag: "Pop", coverTone: "green" },
  { title: "Fireworks", artist: "DAOKO x Kenshi Yonezu", tag: "Movie", coverTone: "sky" },
  { title: "Uchiage Hanabi", artist: "DAOKO x Kenshi Yonezu", tag: "Movie", coverTone: "blue" },
  { title: "Cinderella", artist: "Cidergirl", tag: "Anime", coverTone: "pink" },
  { title: "Palette", artist: "Cidergirl", tag: "Band", coverTone: "mint" },
  { title: "Kanade", artist: "Sukima Switch", tag: "Classic", coverTone: "orange" },
  { title: "Zenryoku Shounen", artist: "Sukima Switch", tag: "Classic", coverTone: "green" },
  { title: "Niji", artist: "Masaki Suda", tag: "Ballad", coverTone: "yellow" },
  { title: "Machigai Sagashi", artist: "Masaki Suda", tag: "Ballad", coverTone: "blue" },
  { title: "Sayonara Elegy", artist: "Masaki Suda", tag: "Rock", coverTone: "black" },
  { title: "Kokoronashi", artist: "Majiko", tag: "Ballad", coverTone: "purple" },
  { title: "Irony", artist: "ClariS", tag: "Anime", coverTone: "pink" },
  { title: "Connect", artist: "ClariS", tag: "Anime", coverTone: "red" },
  { title: "Kimi no Shiranai Monogatari", artist: "supercell", tag: "Anime", coverTone: "sky" },
  { title: "My Dearest", artist: "supercell", tag: "Anime", coverTone: "blue" },
  { title: "Namae no Nai Kaibutsu", artist: "EGOIST", tag: "Anime", coverTone: "black" },
  { title: "Departures", artist: "EGOIST", tag: "Anime", coverTone: "mint" },
  { title: "Database", artist: "MAN WITH A MISSION", tag: "Anime", coverTone: "red" },
  { title: "Raise Your Flag", artist: "MAN WITH A MISSION", tag: "Anime", coverTone: "orange" },
  { title: "Remember Me", artist: "MAN WITH A MISSION", tag: "Rock", coverTone: "green" },
  { title: "Fly High!!", artist: "BURNOUT SYNDROMES", tag: "Anime", coverTone: "yellow" },
  { title: "Hikari Are", artist: "BURNOUT SYNDROMES", tag: "Anime", coverTone: "blue" },
  { title: "Phoenix", artist: "BURNOUT SYNDROMES", tag: "Anime", coverTone: "red" },
  { title: "Touch Off", artist: "UVERworld", tag: "Anime", coverTone: "orange" },
  { title: "D-tecnoLife", artist: "UVERworld", tag: "Anime", coverTone: "black" },
  { title: "Odd Future", artist: "UVERworld", tag: "Anime", coverTone: "purple" },
  { title: "Blue Encount", artist: "Polaris", tag: "Band", coverTone: "sky" },
  { title: "Polaris", artist: "BLUE ENCOUNT", tag: "Anime", coverTone: "blue" },
  { title: "Day x Day", artist: "BLUE ENCOUNT", tag: "Anime", coverTone: "green" },
  { title: "Hello, World!", artist: "BUMP OF CHICKEN", tag: "Anime", coverTone: "yellow" },
  { title: "Aurora", artist: "BUMP OF CHICKEN", tag: "Band", coverTone: "mint" },
  { title: "Tentai Kansoku", artist: "BUMP OF CHICKEN", tag: "Classic", coverTone: "sky" },
  { title: "Butterfly", artist: "BUMP OF CHICKEN", tag: "Band", coverTone: "pink" },
  { title: "Sorairo Days", artist: "Shoko Nakagawa", tag: "Anime", coverTone: "blue" },
  { title: "God Knows...", artist: "Aya Hirano", tag: "Anime", coverTone: "red" },
  { title: "Hare Hare Yukai", artist: "Aya Hirano", tag: "Anime", coverTone: "yellow" },
  { title: "Only My Railgun", artist: "fripSide", tag: "Anime", coverTone: "sky" },
  { title: "Level5 Judgelight", artist: "fripSide", tag: "Anime", coverTone: "purple" },
  { title: "This Game", artist: "Konomi Suzuki", tag: "Anime", coverTone: "red" },
  { title: "Redo", artist: "Konomi Suzuki", tag: "Anime", coverTone: "orange" },
  { title: "Realize", artist: "Konomi Suzuki", tag: "Anime", coverTone: "blue" },
  { title: "The Everlasting Guilty Crown", artist: "EGOIST", tag: "Anime", coverTone: "black" },
  { title: "Great Days", artist: "Karen Aoki & Daisuke Hasegawa", tag: "Anime", coverTone: "green" },
  { title: "Crazy Noisy Bizarre Town", artist: "THE DU", tag: "Anime", coverTone: "purple" },
  { title: "Bloody Stream", artist: "Coda", tag: "Anime", coverTone: "red" },
  { title: "Fukashigi no Carte", artist: "Mai Sakurajima", tag: "Anime", coverTone: "pink" },
  { title: "Seishun Complex", artist: "Kessoku Band", tag: "Anime", coverTone: "yellow" },
  { title: "Guitar, Loneliness and Blue Planet", artist: "Kessoku Band", tag: "Anime", coverTone: "blue" },
  { title: "Distortion!!", artist: "Kessoku Band", tag: "Anime", coverTone: "orange" },
  { title: "If I Could Be a Constellation", artist: "Kessoku Band", tag: "Anime", coverTone: "sky" },
  { title: "Hitoribocchi Tokyo", artist: "Kessoku Band", tag: "Anime", coverTone: "mint" },
  { title: "Daten", artist: "Creepy Nuts", tag: "Anime", coverTone: "purple" },
  { title: "Losstime", artist: "Creepy Nuts", tag: "Hip Hop", coverTone: "black" },
  { title: "Okaeri", artist: "Tani Yuuki", tag: "Pop", coverTone: "green" },
  { title: "Myra", artist: "Tani Yuuki", tag: "Ballad", coverTone: "pink" },
];
